C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
