C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\pjoyc_000\Documents\GitHub\Newtscope\Lower Ring - Aluminum-Static 1
C:\Users\Elizabeth\Documents\GitHub\Newtscope\Netwball V2 Secondary\Secondary mirror mount v2-Static 1
C:\Users\Elizabeth\Documents\GitHub\Newtscope\Netwball V2 Secondary\Secondary mirror mount v2-Static 1
